'use client';

import React, { useState } from 'react';
import { ShieldCheck, Info, ChevronDown, ChevronUp, Compass } from 'lucide-react';

export function Footer() {
  const [expanded, setExpanded] = useState(false);

  return (
    <footer className="w-full border-t border-legal-800/80 bg-legal-950/90 py-6 px-4 sm:px-6 lg:px-8 text-xs text-legal-400">
      <div className="max-w-7xl mx-auto space-y-4">
        {/* Compact Expandable Legal Boundary Component */}
        <div className="surface-card p-3.5 sm:p-4 border-legal-800/80 bg-legal-900/60 transition-all">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-2.5 min-w-0">
              <div className="w-6 h-6 rounded-lg bg-amber-500/10 border border-amber-500/20 flex items-center justify-center text-amber-400 shrink-0">
                <Info className="w-3.5 h-3.5" />
              </div>
              <p className="text-xs text-legal-300 truncate">
                <strong className="text-white font-medium">Important:</strong> Legal Compass helps you understand agreements and prepare for legal review. It does not provide legal advice.
              </p>
            </div>

            <button
              type="button"
              onClick={() => setExpanded(!expanded)}
              className="text-[11px] font-medium text-amber-400 hover:text-amber-300 flex items-center gap-1 shrink-0 px-2 py-1 rounded-lg hover:bg-amber-500/10 transition-colors"
            >
              <span>{expanded ? 'Hide details' : 'Learn more'}</span>
              {expanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
            </button>
          </div>

          {expanded && (
            <div className="mt-3 pt-3 border-t border-legal-800/70 text-xs text-legal-400 leading-relaxed space-y-1.5 animate-fadeIn">
              <p>
                All extractions, citations, risk evaluations, and questions generated by Legal Compass are designed as informational aids to help you understand contractual provisions and prepare structured questions for a licensed attorney.
              </p>
              <p className="text-legal-500 text-[11px]">
                No attorney-client relationship is created by the use of this system. Enforceability and legal standing always depend on applicable jurisdictional statutes and human counsel review.
              </p>
            </div>
          )}
        </div>

        {/* Brand & Guarantee Row */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-1 text-[11px] text-legal-500">
          <div className="flex items-center gap-2">
            <Compass className="w-3.5 h-3.5 text-amber-400/80" />
            <span className="text-legal-300 font-medium">Legal Compass</span>
            <span>•</span>
            <span>Evidence-Grounded Legal Navigation</span>
          </div>

          <p className="text-legal-400 text-center sm:text-right">
            "We do not replace the lawyer. We help you arrive prepared."
          </p>
        </div>
      </div>
    </footer>
  );
}
